### PR TITLE
fix(select): filter prop invalid, closes #3175

### LINKED ISSUE #3175: NSelect filter invalid
### TuSimple/naive-ui version (版本)
2.30.6

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://codepen.io/charl0tter/pen/RwQXQGO?editors=1111

### Reappearance steps (重现步骤)
https://codepen.io/charl0tter/pen/RwQXQGO?editors=1111

### Expected results (期望的结果)
能够正常调用过滤器函数

### Actual results (实际的结果)
不能正常调用过滤器函数

### PR DESCRIPTION
**Pull request by jizai1125**
close #3175

### CODE REVIEW

File: src/select/src/Select.tsx [hunk 1]
```diff
@@ -340,7 +340,7 @@ export default defineComponent({
         } else {
           return filterOptions(
             localOptions,
-            resolvedFilterRef.value,
+            props.filter || resolvedFilterRef.value,
```
Comment (07akioni) [inline src/select/src/Select.tsx:343]:
```suggestion
            resolvedFilterRef.value,
```
