### PR TITLE
fix(data-table): td-color-hover is incorrect

### LINKED ISSUE #1686: td-color-hover should be darker than td-color-striped
### TuSimple/naive-ui version (版本)
2.21.1

### Vue version (Vue 版本)
3.2.23

### Browser and its version (浏览器及其版本)
Mozilla Firefox 94.0.2

### System and its version (系统及其版本)
Arch Linux 5.15.4-zen1-1-zen

### Reappearance link (重现链接)
https://codesandbox.io/s/naive-ui-td-color-hovered-demo-rgppd?file=/src/App.vue

### Reappearance steps (重现步骤)
Create a data table with the `striped` option

### Expected results (期望的结果)
`td-color-hover` should be darker than `td-color-striped`

### Actual results (实际的结果)
`td-color-hover` is the same as `td-color-striped`

### PR DESCRIPTION
**Pull request by Talljack**
close #1686

### CODE REVIEW

File: src/_styles/common/light.ts [hunk 1]
```diff
@@ -177,7 +177,8 @@ const derived = {
 
   hoverColor: 'rgb(243, 243, 245)',
   // use color with alpha since it can be nested with header filter & sorter effect
-  tableColorHover: 'rgba(0, 0, 100, 0.02)',
+  tableColorHover: 'rgba(0, 0, 100, 0.03)',
+  tableStripedColor: 'rgba(0, 0, 100, 0.02)',
```
Comment (07akioni) [inline src/_styles/common/light.ts:181]:
```suggestion
  tableColorStriped: 'rgba(0, 0, 100, 0.02)',
```
