### PR TITLE
fix(input-number): input-number cannot update when integer end with 0

### LINKED ISSUE #2115: 输入以0结尾的数字时不会触发on-update:value事件
### TuSimple/naive-ui version (版本)
2.23.2

### Vue version (Vue 版本)
3.0.0

### Browser and its version (浏览器及其版本)
Chrome/96.0.4664.110

### System and its version (系统及其版本)
Windows NT 10.0

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/input-number

### Reappearance steps (重现步骤)
官方文档 数字输入 Input Number 演示-事件 在输入框中输入 1 时 显示吐司 update:value(1)
再输入 0 时 不会弹出吐司 直到输入非 0 数字 才会 弹出吐司 update:value(xx)

### Expected results (期望的结果)
在输入 0 时正常触发事件update:value

### Actual results (实际的结果)
在输入以0结尾的数字时不会触发update:value事件

### PR DESCRIPTION
**Pull request by Talljack**
close #2115

### CODE REVIEW

File: src/input-number/src/utils.ts [hunk 1]
```diff
@@ -12,9 +12,9 @@ export function parse (value: string): number | null {
 }
 
 // can be parsed to number but shouldn't be applied when inputing
-// Ending with 0 and. doesn't update, if 0 parse func will remove 0
+// when value includes ., ending with 0 and. doesn't update, if 0 parse func will remove 0
```
Comment (07akioni) [inline src/input-number/src/utils.ts:15]:
```suggestion
// when value includes `.`, ending with 0 and`.`, doesn't update, if 0 parse func will remove 0
```
