### PR TITLE
fix(data-table): The filter will not take effect when the `filterOptions` value is 0

### LINKED ISSUE #2392: 数据表格过滤器选项值为数值0时，过滤条件不生效。
### TuSimple/naive-ui version (版本)
2.25.2

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Edge(98.0.1108.43)

### System and its version (系统及其版本)
Windows 11(22000.493)

### Reappearance link (重现链接)
https://codesandbox.io/s/hungry-paper-0np9q

### Reappearance steps (重现步骤)
使用数据表格组件。
设置过滤器条件为数值0。
选择过滤条件0.

### Expected results (期望的结果)
正确的显示过滤器图标已选择状态及已选中值。
正确过滤数据。

### Actual results (实际的结果)
过滤器图标未正确显示已选择状态。
过滤器选项未正确选中已选择值。
数据未正确过滤。

### PR DESCRIPTION
**Pull request by amadeus711**
close #2392

### CODE REVIEW

File: src/data-table/src/use-table-data.ts [hunk 1]
```diff
@@ -85,7 +85,7 @@ export function useTableData (
     columnsWithControlledFilter.forEach((column) => {
       if (column.type === 'selection' || column.type === 'expand') return
       controlledFilterState[column.key] =
-        column.filterOptionValues || column.filterOptionValue || null
+        column.filterOptionValues ?? column.filterOptionValue ?? null
```
Comment (07akioni) [inline src/data-table/src/use-table-data.ts:88]: 其实还是有点问题，得用 undefined 来拦截，null 应该是受控的，就刻意为空
