### PR TITLE
fix(calendar): disabled cells are clickable

### LINKED ISSUE #2686: Disabled cells should not be clickable in Calendar component.
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Chrome(99.0.4844.74)(arm64)

### System and its version (系统及其版本)
MacOs(12.0.1)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/calendar

### Reappearance steps (重现步骤)
Click the disabled cell in Calendar component.

### Expected results (期望的结果)
Disabled cells should not be clickable in Calendar component.

### Actual results (实际的结果)
Disabled cells are clickable.

### PR DESCRIPTION
**Pull request by amadeus711**
close #2686

### CODE REVIEW

**Review by Talljack — APPROVED** [review]

File: src/calendar/src/Calendar.tsx [hunk 1]
```diff
@@ -277,19 +277,24 @@ export default defineComponent({
...
               const selected = normalizedValue === startOfDay(ts).valueOf()
               return (
                 <div
                   key={isCurrentDate ? 'current' : index}
                   class={[
                     `${mergedClsPrefix}-calendar-cell`,
-                    disabled && `${mergedClsPrefix}-calendar-cell--disabled`,
+                    (notInCurrentMonth || disabled) &&
+                      `${mergedClsPrefix}-calendar-cell--disabled`,
+                    disabled && `${mergedClsPrefix}-calendar-cell--no-drop`,
```
Comment (07akioni) [inline src/calendar/src/Calendar.tsx:291]: No need for the class. You can write cursor style into disabled class.

File: src/calendar/src/styles/index.cssr.ts [hunk 2]
```diff
@@ -120,6 +120,7 @@ export default c([
           `)
         ])
       ]),
+      cM('no-drop', 'cursor: no-drop;'),
```
Comment (07akioni) [inline src/calendar/src/styles/index.cssr.ts:123]: image

use not-allowed

In semantic, it should be not-allowed
